{{- if .Values.configMaps }}
  {{- range $configMapName, $config := .Values.configMaps }}
---
# ConfigMap for {{ $configMapName }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $configMapName }}
  namespace: {{ $.Values.nameSpace }}
data:
  {{- range $key, $value := $config.yaml }}
  {{ $key }}: |
  {{ $value | toString | nindent 4 }}
  {{- end }}
  {{- end }}
  {{- end }}
