# templates/cronjob.yaml
{{- range .Values.cronJobs }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ $.Release.Name }}-{{ .name }}
  namespace: {{ $.Values.nameSpace }}
spec:
  schedule: {{ .schedule | quote }}
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          imagePullSecrets:
            {{- toYaml $.Values.imagePullSecrets | nindent 12 }}
          containers:
            - name: {{ .name }}
              image: {{ $.Values.image.name }}:{{ $.Values.image.tag }}
              imagePullPolicy: {{ $.Values.image.pullPolicy }}
              command:
              {{- range .command }}
                - {{ . | quote }}
              {{- end }}
              env:
              {{- range $key, $value := $.Values.runVars }}
                - name: {{ $key }}
                  value: {{ $value | quote }}
              {{- end }}
              resources:
                {{- toYaml $.Values.resources | nindent 16 }}
              volumeMounts:
              {{- range $.Values.deploymentConfigMaps }}
                - name: {{ .configMapName }}
                  mountPath: {{ .mountPath }}/{{ .name }}
                  subPath: {{ .name }}
              {{- end }}
              {{- range $.Values.deploymentVolumes }}
                - name: {{ .name }}
                  mountPath: {{ .mountPath }}
              {{- end }}
          volumes:
          {{- range $.Values.deploymentConfigMaps }}
            - name: {{ .configMapName }}
              configMap:
                name: {{ $.Release.Name }}-{{ .configMapName }}
          {{- end }}
          {{- range $.Values.deploymentVolumes }}
            - name: {{ .name }}
              nfs:
                server: {{ .server }}
                path: {{ .share }}
          {{- end }}
{{- end }}
