# templates/ingress.yaml
{{- if .Values.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  namespace: {{ .Values.nameSpace }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          {{- if .Values.ingress.paths }}
          {{- range .Values.ingress.paths }}
            - path: {{ . }}
              pathType: Prefix
              backend:
                service:
                  name: {{ $.Release.Name }}
                  port:
                    number: {{ index $.Values.ports 0 }}
          {{- end }}
          {{- else }}
          - path: {{ .Values.ingress.path | default "/" }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}
                number: {{ index $.Values.ports 0 }}
          {{- end }}
          {{- if .Values.remoteProxy.enabled }}
          {{- range .Values.remoteProxy.paths }}
          - path: {{ .path }}
            pathType: Prefix
            backend:
              service:
                name: {{ $.Release.Name }}-{{ .name }}
                port:
                  number: {{ .port }}
          {{- end }}
          {{- end }}
{{- end }}
