name: Publish helmchart (universal)

on:
  pull_request:
  workflow_dispatch:

env:
  CHART_NAME: "universal"

jobs:
  publish:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            chart-yaml:
              - '${{ env.CHART_NAME }}/Chart.yaml'

      - name: Set environment variables
        id: set-variables
        run: |
          echo "REPOSITORY=ghcr.io/$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_OUTPUT"
          echo "VERSION=$(yq -r .version ./${{ env.CHART_NAME }}/Chart.yaml)" >> "$GITHUB_OUTPUT"

      - name: Syntax check
        run: |
          helm template ./${{ env.CHART_NAME }}

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Package and push Helm chart
        if: steps.changes.outputs.chart-yaml == 'true'
        run: |
          helm package ./${{ env.CHART_NAME }} --version ${{ steps.set-variables.outputs.VERSION }}
          helm push ./${{ env.CHART_NAME }}-${{ steps.set-variables.outputs.VERSION }}.tgz oci://${{ steps.set-variables.outputs.REPOSITORY }}
